### ISSUE TITLE
SSL certificate error on a feed

### ISSUE THREAD

**Issue by Riduidel** [tontof/kriss_feed#356]
Since ~ 3 weeks, the tao of mac feed (located at http://taoofmac.com/rss) can't load in krissfeed.

In update page, the error message is

    SSL certificate problem, verify that the CA cert is OK. Details: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

krissefeed is installed on ny NAS, running on lighttpd.

What can I do to revoke the incorrect certificate ?

**Comment by tontof** [comment]
I guess it was https instead of http in your comment.

To correct the SSL problem you need to add the used certificate on your NAS and add it using
```curl_setopt($ch, CURLOPT_CAINFO, "/etc/cacert.pem");```
You can ignore the certificate check (but it's not recommended) with
```curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);```
But more simply you can add the http://taoofmac.com/rss instead of https://taoofmac.com/rss

You will maybe have other problem as the feed is invalid:
http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Ftaoofmac.com%2Frss

**Comment by Riduidel** [comment]
OK, switching to standard HTTP fixed the issue.
