### ISSUE TITLE
License

### ISSUE THREAD

**Issue by n8225** [tontof/kriss_feed#375]
I am working on updating the listing of Kriss Feed on [https://github.com/Kickball/awesome-selfhosted](https://github.com/Kickball/awesome-selfhosted).  I noticed in the Readme that Kriss Feed is free software but it doesn't clearly specify the terms of the license.  Could you please clarify this.

**Comment by tontof** [comment]
I'm sorry, I don't know what I can reply to your mail.
I've already explained in an article (in French) : 
http://tontof.net/index.php?2013/09/12/18/15/11-licence-de-kriss-feed
that for me choosing a license is useless and so I just don't want to 
pick one randomly.
I let people to do what they want with my code, a license does not 
protect stupid people to do stupid things.
Maybe I should add all existing licenses and let people to choose the 
license they want...
You're not the only one who is asking me to precise that...
--
Tontof

Le dim. 28 août 2016 à 22:05, n8225 <notifications@github.com> a 
écrit :

**Comment by fpunktk** [comment]
Perhaps this is the license you want: https://en.wikipedia.org/wiki/WTFPL

**Comment by nodiscc** [comment]
or https://creativecommons.org/choose/zero/

**Comment by tontof** [comment]
I already know these licenses, there is also the unlicense, that's not really the point.
What about if I had something like, there is no specific license and I let people to choose the one they need/want. As a lot of work come with 2 licences (MIT/GPL) I guess I can not add all the existing licences even if I've thought about that.
Unfortunately it's not possible to be exhaustive and I did not do that.

**Comment by tontof** [comment]
I guess that way you can add all the licences you refer in https://github.com/Kickball/awesome-selfhosted#list-of-licenses to KrISS feed ?

**Comment by nodiscc** [comment]
Apparently when you release a work under Public Domain/CC0, you grant the licensee _all_ rights, including the right to relicense under whatever license they want. https://opensource.stackexchange.com/questions/4235/how-do-i-turn-a-public-domain-project-into-a-mit-project

I can try to gather more info if you want, but by reading http://tontof.net/index.php?2013/09/12/18/15/11-licence-de-kriss-feed I believe CC0/Public Domain is what you need.

**Comment by tontof** [comment]
That's the problem, Public Domain/CC0/WTFPL/Unlicence/Beerware why choosing one specific ?
```no license=all rights reserved``` and if I write ```all licences``` would it mean ```no rights reserved``` ?

**Comment by tontof** [comment]
What are you doing when you find code on Stackoverflow ? Do you really ask the author which licence (s)he published the code in order to use it ? For me that's the same. My github projects are here because I've coded for myself and wanted to share. That's all. Even in my code I use some code from people I don't even know which license they use. I add a comment to remember where I find it:
https://github.com/tontof/kriss_feed/search?utf8=%E2%9C%93&q=stackoverflow
Suppose I choose CC0 but the author of the code I used wanted a GPL. That would not be authorized I guess ? Well I know that could be problematic for your awesome-selfhosted where you put a tag on each project. But that's why I guess the proposition I've suggested https://github.com/tontof/kriss_feed/issues/375#issuecomment-245717302 is the really best option I can think about.

**Comment by nodiscc** [comment]
> What are you doing when you find code on Stackoverflow ?

footer:  site design / logo © 2016 Stack Exchange Inc; user contributions licensed under cc by-sa 3.0 with attribution required. So putting the url in a comment is fine.

> Suppose I choose CC0 but the author of the code I used wanted a GPL. That would not be authorized I guess 

Apparently [no](https://programmers.stackexchange.com/questions/159023/can-cc0-code-use-a-gpl-library). But with the "any license you want" case you suggest, this would also not be permitted. GPL is a restrictive Free Software license.

> awesome-selfhosted where you put a license tag on each project

I'll just use a CC0 tag since you agree that it can be relicensed, modified and used for whatever purpose (which is the point of CC0).

> why choosing one specific
>all licences would it mean no rights reserved ?

No. Different licenses imply different restrictions, licensing a work under "all licenses" would have no validity since they would contradict. That's why most people choose 1 license, because we are not lawyers and smarter people figured out the legal terms for us. You can write your own license but it would not necessarily have legal validity. Again, if you want to waive all rights, just use Public Domain/CC0.

**Comment by tontof** [comment]
You're right I'm not a lawyer and I guess you're right.
If you read my article you should have seen this link:
http://www.blender.org/blenderorg/blender-foundation/press/re-branding-blender
I don't think adding an explicit license is useful for my code on github.
I will not try to debate, I understand your point but I don't care the license stuff and let smarter people to figure out legal terms for whoever want.
For your point I see 2 solutions:
- If you want to add Public Domain/CC0 on awesome-selfhosted for KrISS feed, I'm OK with that but I won't add it on my code.
- If awesome-selfhosted should list only project with explicit license, I guess you will have to remove KrISS feed from your list. That's your issue https://github.com/Kickball/awesome-selfhosted/issues/145 not mine...

**Comment by nodiscc** [comment]
Yes you are right that a license text will prevent noone from actually copying/ripping off/rebranding/selling parts or whole of your software (though it sometimes [happens](http://www.infoworld.com/article/2893695/open-source-software/vmware-heading-to-court-over-gpl-violations.html)). No problem about not adding it to the git repository, since you seem to agree on the terms, we will list it as CC0. Users can figure out the license by reading this issue. Thank you for replying, and for creating this nice project !
