### ISSUE TITLE
Aggregated outgoing feed possible?

### ISSUE THREAD

**Issue by poVoq** [tontof/kriss_feed#397]
Is there an option to have all feeds combined in one outgoing ATOM and/or RSS feed?

That way one could display the latest entries easily in another website's widget or add such an aggregated feed to an external mobile reader or so.

Selfoss has this option, but it is undocumented :)

**Comment by tontof** [comment]
No option for that and I guess the best thing to do is to create a separate php file that read the KrISS feed data file to generate that kind of RSS. It will not be available inside KrISS feed as for my point of view that's not a common behavior for a RSS reader and is too specific. That's why the separate PHP file is the best option for now (I aim to refactor my KrISS feed code with a new MVVM approach using https://github.com/kriss/mvvm and I hope that this kind of behavior will be possible using a plugin)

I don't know if you can code in PHP, but to create a separate file, a good starting point is the readData file: https://github.com/tontof/kriss_feed/blob/master/src/bin/readData.php

**Comment by poVoq** [comment]
Ok, understandable. I'll probably point my widget to the Shaarli feed instead and just link to KrISS feed reader for "more updates".
Thanks!
