### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by doc75** [tontof/kriss_feed#420]
I tried to run KrissFeed with PHP 8.0, but failed with an error message related to `undefined function get_magic_quotes_gpc`.

I checked in the repo and realised that the fixes to get [PHP 7.4 working](https://github.com/tontof/kriss_feed/commit/73c1ed1c03491a090873e039f150280694d9ddbc) (and that should allow also the code to work with 8.0) are not yet in index.php.
Do you plan to re-generate an updated version of index.php (I could rebuild it myself, but I am relying on the stable version you provide usually ;-) ) ?

Thanks for this great software.

**Comment by doc75** [comment]
Perhaps I should use `src/index.php` instead. But I am not sure what is the difference between `index.php` and `src/index.php` in term of intent (dev vs. stable ?).

**Comment by tontof** [comment]
You're right, ```src/index.php``` is the future version and correspond to the dev one while the ```index.php``` is the last released version.
That's great it works with PHP 8.0 I don't have this version yet and did not test myself. Maybe I should update ```index.php``` so that it corresponds to the last dev version as I did not plan modification for now.
Thanks for your feedback!

**Comment by doc75** [comment]
Issue solved by using the 8.11 version
